<a href="https://colab.research.google.com/github/tornadopath/data-science-bootcamp/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.__version__

'2.2.2'

In [2]:
s = pd.Series([1, 2, 4, 7])
s

0    1
1    2
2    4
3    7
dtype: int64

In [7]:
s = pd.Series(data=[1, 2, 4, 7], index=['a', 'b', 'c', 'd'], name='sample')
s

a    1
b    2
c    4
d    7
Name: sample, dtype: int64

In [8]:
import numpy as np #brak danych

np.nan

nan

In [9]:
s = pd.Series(data=[1, np.nan, 4, 7], index=['a', 'b', 'c', 'd'], name='sample')
s

a    1.0
b    NaN
c    4.0
d    7.0
Name: sample, dtype: float64

In [12]:
s = pd.Series(data=[True, False, False])
s

0     True
1    False
2    False
dtype: bool

In [32]:
import numpy as np   #daty
s = pd.Series(data=np.arange(10, 20), index= pd.date_range(start= '20260202', periods=10))
s
list(s.index) #przekonwertowanie na listę

[Timestamp('2026-02-02 00:00:00'),
 Timestamp('2026-02-03 00:00:00'),
 Timestamp('2026-02-04 00:00:00'),
 Timestamp('2026-02-05 00:00:00'),
 Timestamp('2026-02-06 00:00:00'),
 Timestamp('2026-02-07 00:00:00'),
 Timestamp('2026-02-08 00:00:00'),
 Timestamp('2026-02-09 00:00:00'),
 Timestamp('2026-02-10 00:00:00'),
 Timestamp('2026-02-11 00:00:00')]

obiekty część 2

In [27]:
s = pd.Series(data=['python', 'java', ' c '], name='languages')
s

0    python
1      java
2        c
Name: languages, dtype: object

In [26]:
s.index

DatetimeIndex(['2026-02-02', '2026-02-03', '2026-02-04', '2026-02-05',
               '2026-02-06', '2026-02-07', '2026-02-08', '2026-02-09',
               '2026-02-10', '2026-02-11'],
              dtype='datetime64[ns]', freq='D')

In [30]:
s.values ##wartości
#list(s.values)

array(['python', 'java', ' c '], dtype=object)

In [33]:
s.dtype

dtype('int64')

In [34]:
s.shape

(10,)

Praca z obiektem - wycinanie

In [46]:
price = pd.Series(data={'Apple': 200, 'intellia':12, 'Crispr':60, 'KGHM':np.nan})
price

Apple       200.0
intellia     12.0
Crispr       60.0
KGHM          NaN
dtype: float64

In [38]:
price['intellia'] #lub index

np.int64(12)

In [40]:
price.count() #zliczanie obiektów

np.int64(3)

In [49]:
price.value_counts(dropna=False) ### WAŻNE, LICZY ILE RAZY COŚ WYSTAPIŁO, dropna - liczy rowniez brak danych

200.0    1
12.0     1
60.0     1
NaN      1
Name: count, dtype: int64

In [42]:
price.sum()

np.int64(272)

In [44]:
price.max()

200

In [47]:
price.describe()

count      3.000000
mean      90.666667
std       97.679749
min       12.000000
25%       36.000000
50%       60.000000
75%      130.000000
max      200.000000
dtype: float64

In [53]:
price.nlargest(1) #najwyższa wartość

Apple    200.0
dtype: float64

In [54]:
price.nsmallest(2)

intellia    12.0
Crispr      60.0
dtype: float64

In [55]:
price.rank() - #uporzadkowanie

Apple       3.0
intellia    1.0
Crispr      2.0
KGHM        NaN
dtype: float64

In [57]:
price.sort_values(ascending=False) #sortowanie

Apple       200.0
Crispr       60.0
intellia     12.0
KGHM          NaN
dtype: float64

In [61]:
#metoda apply
price_pln = price.apply(lambda x: x * 3.8)

In [63]:
price_pln

Apple       760.0
intellia     45.6
Crispr      228.0
KGHM          NaN
dtype: float64

dataframe

In [64]:
df = pd.DataFrame(data=[12, 12, 32])
df

    0
0  12
1  12
2  32

In [66]:
df = pd.DataFrame(data=[12, 12, 32], index=['first', 'second', 'third'], columns=['col_1'])
df

        col_1
first      12
second     12
third      32

In [67]:
df = pd.DataFrame(data={'WIG20': ['PKN ORLEN', 'PKO BP'],
                        'mWIG40': ['Amica', 'Playway']})
df
#

       WIG20   mWIG40
0  PKN ORLEN    Amica
1     PKO BP  Playway

In [73]:
df = pd.DataFrame(data=[[10,13,23], [34, 34, 56]], index=['first', 'second'], columns=['col_1', 'col_2', 'col_3'])
df

        col_1  col_2  col_3
first      10     13     23
second     34     34     56

In [74]:
df.columns #zdraca nazwe kolumn

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [76]:
df.index

Index(['first', 'second'], dtype='object')

In [77]:
df.values

array([[10, 13, 23],
       [34, 34, 56]])

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, first to second
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_1   2 non-null      int64
 1   col_2   2 non-null      int64
 2   col_3   2 non-null      int64
dtypes: int64(3)
memory usage: 172.0+ bytes

In [80]:
df.describe()

           col_1      col_2      col_3
count   2.000000   2.000000   2.000000
mean   22.000000  23.500000  39.500000
std    16.970563  14.849242  23.334524
min    10.000000  13.000000  23.000000
25%    16.000000  18.250000  31.250000
50%    22.000000  23.500000  39.500000
75%    28.000000  28.750000  47.750000
max    34.000000  34.000000  56.000000

In [ ]:
#selekcja kolumn i zmiennych

In [81]:
df

        col_1  col_2  col_3
first      10     13     23
second     34     34     56

In [88]:
df['col_1']

first     10
second    34
Name: col_1, dtype: int64

In [ ]:
#zmiana nazwy kolumn

In [90]:
df.columns = ['a', 'b', 'c']
df

         a   b   c
first   10  13  23
second  34  34  56

In [92]:
df.a #wycinanie ale mniej praktyczne, bo jak jest spacja w nazwie kolumny sie robia kłopoty - użyć podkreśnika

first     10
second    34
Name: a, dtype: int64

In [94]:
df['d'] = df.a + df.c #dodawanie kolumny
df

         a   b   c   d
first   10  13  23  33
second  34  34  56  90

In [95]:
df = pd.DataFrame(data=[[10,13,23], [34, 34, 56]], index=['first', 'second'], columns=['col_1', 'col_2', 'col_3'])
df

        col_1  col_2  col_3
first      10     13     23
second     34     34     56

In [96]:
df.loc['first'] #wycinanie po wierszach/indexach , można uzyc numer indexu

col_1    10
col_2    13
col_3    23
Name: first, dtype: int64

In [98]:
#df.loc['first', 'col_2']
df.loc[:, 'col_2'] #bierzesz wszystkie indexy

first     13
second    34
Name: col_2, dtype: int64